# Generated by Django 5.1.1 on 2024-10-19 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfoodpreference",
            unique_together={("user", "fdc_id")},
        ),
        migrations.AlterUniqueTogether(
            name="userfoodrestriction",
            unique_together={("user", "fdc_id")},
        ),
    ]
