# Generated by Django 5.1.1 on 2024-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_alter_userfoodpreference_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbridgedFoodNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.FloatField()),
                ("name", models.CharField()),
                ("amount", models.FloatField()),
                ("unit_name", models.CharField()),
                ("derivation_code", models.CharField()),
                ("derivation_description", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="AbridgedFoodItem",
            fields=[
                ("fdc_id", models.IntegerField(primary_key=True, serialize=False)),
                ("data_type", models.CharField()),
                ("description", models.CharField()),
                ("publication_date", models.DateField()),
                ("brand_owner", models.CharField(null=True)),
                ("gtin_upc", models.CharField(null=True)),
                ("nbd_number", models.CharField(null=True)),
                ("food_code", models.CharField(null=True)),
                ("nutrients", models.ManyToManyField(to="foods.abridgedfoodnutrient")),
            ],
        ),
    ]
