# Generated by Django 5.1.1 on 2024-10-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_labelnutrients_abridgedbrandedfooditem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abridgedbrandedfooditem",
            name="serving_size_unit",
            field=models.CharField(),
        ),
    ]
