# Generated by Django 5.1.1 on 2024-10-21 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0005_alter_abridgedbrandedfooditem_serving_size_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodNutrient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.FloatField()),
                ("name", models.CharField()),
                ("rank", models.IntegerField()),
                ("unit_name", models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name="abridgedbrandedfooditem",
            name="ingredients",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="abridgedbrandedfooditem",
            name="nutrients",
            field=models.ManyToManyField(to="foods.foodnutrient"),
        ),
        migrations.AddField(
            model_name="foodnutrient",
            name="nutrient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foods.nutrient"
            ),
        ),
    ]
