# Generated by Django 5.1.1 on 2024-10-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0006_foodnutrient_nutrient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abridgedbrandedfooditem",
            old_name="nutrients",
            new_name="food_nutrients",
        ),
    ]
