# Generated by Django 5.1.1 on 2024-10-21 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0007_rename_nutrients_abridgedbrandedfooditem_food_nutrients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abridgedbrandedfooditem",
            name="label_nutrients",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="foods.labelnutrients",
            ),
        ),
    ]
