# Generated by Django 5.1.1 on 2024-10-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0008_alter_abridgedbrandedfooditem_label_nutrients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abridgedbrandedfooditem",
            name="serving_size",
            field=models.FloatField(),
        ),
    ]
