# Generated by Django 5.1.1 on 2024-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0009_alter_abridgedbrandedfooditem_serving_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelnutrients",
            name="calcium",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="calories",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="carbohydrates",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="cholesterol",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="fat",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="fiber",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="iron",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="potassium",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="protein",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="saturated_fat",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="sodium",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="sugars",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="labelnutrients",
            name="trans_fat",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
