# Generated by Django 5.1.1 on 2024-11-06 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0011_alter_labelnutrients_calcium_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfoodpreference",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userfoodrestriction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userfoodpreference",
            name="food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="foods.abridgedbrandedfooditem",
            ),
        ),
        migrations.AddField(
            model_name="userfoodrestriction",
            name="food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="foods.abridgedbrandedfooditem",
            ),
        ),
        migrations.RemoveField(
            model_name="userfoodpreference",
            name="fdc_id",
        ),
        migrations.RemoveField(
            model_name="userfoodrestriction",
            name="fdc_id",
        ),
    ]
