# Generated by Django 5.1.1 on 2024-11-06 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0012_alter_userfoodpreference_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfoodpreference",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foods.abridgedbrandedfooditem",
            ),
        ),
        migrations.AlterField(
            model_name="userfoodrestriction",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="foods.abridgedbrandedfooditem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userfoodpreference",
            unique_together={("user", "food")},
        ),
        migrations.AlterUniqueTogether(
            name="userfoodrestriction",
            unique_together={("user", "food")},
        ),
    ]
