# Generated by Django 5.1.1 on 2024-10-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfitnessprofile",
            name="daily_calorie_goal",
        ),
        migrations.AddField(
            model_name="userfitnessprofile",
            name="goal_weight_velocity",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="userfitnessprofile",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="userfitnessprofile",
            name="sex",
            field=models.CharField(choices=[("M", "Male"), ("F", "Female")], null=True),
        ),
        migrations.AlterField(
            model_name="userfitnessprofile",
            name="activity_level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Sedentary"),
                    (300, "Lightly Active"),
                    (500, "Moderately Active"),
                    (700, "Very Active"),
                ],
                null=True,
            ),
        ),
    ]
