# Generated by Django 5.1.1 on 2024-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userfitnessprofile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfitnessprofile",
            name="daily_calorie_goal",
            field=models.FloatField(null=True),
        ),
    ]
